# Generated by Django 4.2.16 on 2024-10-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_participation"),
    ]

    operations = [
        migrations.RenameField(model_name="event", old_name="name", new_name="title",),
    ]
